services:
    phpbbstudio.dol.listener:
        class: phpbbstudio\dol\event\main_listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }

    auth.provider.oauth.service.studio_discord:
        class: phpbbstudio\dol\auth\provider\oauth\service\discord
        arguments:
            - '@config'
            - '@language'
            - '@request'
        tags:
            - { name: auth.provider.oauth.service }
